#! /usr/bin/python3

# SPDX-FileCopyrightText: © 2023 Tenstorrent Inc.
# SPDX-License-Identifier: GPL-2.0-only

import fileinput
import re

empty_with_spaces_re = re.compile('^\\s+$')     # Lines that contain whitespace but no nonspaces
trailing_whitespace_re = re.compile('\\S\\s+$') # Lines that contain trailing whitespace
tab_after_space = re.compile('^\\s* \t')        # Lines where the leading whitespace contains a tab after a space
consecutive_spaces = re.compile(' {8}')         # Lines that contain 8 consecutive spaces

for line in fileinput.input():
    line = line.rstrip('\n')

    if empty_with_spaces_re.search(line):
        print(f'{fileinput.filename()}:{fileinput.filelineno()}: contains whitespace but no nonspaces.')

    if trailing_whitespace_re.search(line):
        print(f'{fileinput.filename()}:{fileinput.filelineno()}: contains trailing whitespace.')

    if tab_after_space.search(line):
        print(f'{fileinput.filename()}:{fileinput.filelineno()}: the leading whitespace contains a tab after a space.')

    if consecutive_spaces.search(line):
        print(f'{fileinput.filename()}:{fileinput.filelineno()}: contains 8 consecutive spaces.')
