#! /bin/bash

set -e

if [ $# -ne 0 ]; then
    echo "No command-line parameters are accepted."
    exit 1
fi

TTDRIVER_REL="/mnt/motor/syseng/ttdriver-rel"

if [ ! -d "$TTDRIVER_REL" ]; then
    echo "No access to $TTDRIVER_REL, is motor mounted?"
    exit 1
fi

PACKAGE_VERSION=$(sed -nE "s/^[[:space:]]*PACKAGE_VERSION[[:space:]]*=[[:space:]]*\"([^\"]+)\"/\\1/p" dkms.conf)
ARCHIVE=$(tools/make-source-release -m)
ARCHIVE_BASENAME=$(basename "$ARCHIVE")

TARGET="$TTDRIVER_REL/$PACKAGE_VERSION"

mkdir -p "$TARGET"
cp "$ARCHIVE" "$TARGET/$ARCHIVE_BASENAME"

INSTALL_SCRIPT="$TARGET/install_ttkmd_$PACKAGE_VERSION.bash"

cat tools/installer-header.sh > "$INSTALL_SCRIPT"
gzip -cn9 "$ARCHIVE" >> "$INSTALL_SCRIPT"

chmod a+x "$INSTALL_SCRIPT"

echo "Deployed to $TARGET."
