#! /bin/bash

set -e

TTDRIVER_REL="/mnt/motor/syseng/ttdriver-rel"

if [ $# -gt 1 ]; then
    echo "Usage: make-motor-release [target-dir]"
    echo "Default target-dir is ${TTDRIVER_REL}/DRIVER_VERSION."
    exit 1
fi

PACKAGE_VERSION=$(sed -nE "s/^[[:space:]]*PACKAGE_VERSION[[:space:]]*=[[:space:]]*\"([^\"]+)\"/\\1/p" dkms.conf)
ARCHIVE=$(tools/make-source-release -m)
ARCHIVE_BASENAME=$(basename "$ARCHIVE")

if [ $# -eq 1 ]; then
    TARGET="$1"
else
    if [ ! -d "$TTDRIVER_REL" ]; then
        echo "No access to $TTDRIVER_REL, is motor mounted?"
        exit 1
    fi

    TARGET="$TTDRIVER_REL/$PACKAGE_VERSION"
fi

mkdir -p "$TARGET"
cp "$ARCHIVE" "$TARGET/$ARCHIVE_BASENAME"

INSTALL_SCRIPT="$TARGET/install_ttkmd_$PACKAGE_VERSION.bash"

cat tools/installer-header.sh > "$INSTALL_SCRIPT"
gzip -cn9 "$ARCHIVE" >> "$INSTALL_SCRIPT"

chmod a+x "$INSTALL_SCRIPT"

echo "Deployed to $TARGET."
