name: Build RHEL/Rocky

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

jobs:
  build-rocky:
    name: Build on Rocky Linux ${{ matrix.version }}
    strategy:
      fail-fast: false
      matrix:
        version: [9]
    runs-on: ubuntu-latest
    container:
      image: rockylinux:${{ matrix.version }}
    steps:
      - name: Install build dependencies
        run: |
          dnf install -y epel-release
          dnf install -y make gcc kernel-devel elfutils-libelf-devel
          
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Find kernel version
        run: |
          ls -la /usr/src/kernels/
          KERNEL_VER=$(ls /usr/src/kernels/ | grep -v '^\.' | head -n 1)
          echo "Found kernel version: ${KERNEL_VER}"
          if [ -z "${KERNEL_VER}" ]; then
            echo "ERROR: No kernel version found!"
            exit 1
          fi
          echo "KERNEL_VER=${KERNEL_VER}" >> $GITHUB_ENV
      
      - name: Build kernel module
        run: |
          echo "Building against kernel: ${KERNEL_VER}"
          make -C /usr/src/kernels/${KERNEL_VER} M=$(pwd) modules
      
      - name: Verify build
        run: |
          ls -lh tenstorrent.ko
