name: mass-build-test

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    mass-build-test:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - run: |
                sudo apt update
                sudo apt install -y dkms git libelf-dev
                git clone https://github.com/gregkh/linux /tmp/linux
                latest_release=$(git -C /tmp/linux tag --sort=-version:refname | awk '/^v[0-9]+\.[0-9]+$/ { print; exit }')
                test -n "$latest_release"
                test/mass-build-test . /tmp/linux v5.4 "$latest_release"
